export interface TacoEntry {
  id: number;
  nome: string;
  categoria: string;
  energia_kcal: number;
  proteina_g: number;
  lipideos_g: number;
  carboidrato_g: number;
  fibra_alimentar_g: number;
  calcio_mg: number;
  ferro_mg: number;
  zinco_mg: number;
  vitamina_c_mg: number;
  vitamina_a_ra: number;
  porcao: string;
  medida_caseira: string;
}

export const tacoDatabase: TacoEntry[] = [
  {
    id: 1,
    nome: "Arroz branco cozido",
    categoria: "Cereais e derivados",
    energia_kcal: 130,
    proteina_g: 2.7,
    lipideos_g: 0.3,
    carboidrato_g: 28,
    fibra_alimentar_g: 0.4,
    calcio_mg: 5,
    ferro_mg: 0.4,
    zinco_mg: 0.4,
    vitamina_c_mg: 0,
    vitamina_a_ra: 0,
    porcao: "100g",
    medida_caseira: "2 colheres de sopa",
  },
  {
    id: 2,
    nome: "Feijão preto cozido",
    categoria: "Leguminosas",
    energia_kcal: 77,
    proteina_g: 4.8,
    lipideos_g: 0.5,
    carboidrato_g: 14,
    fibra_alimentar_g: 5.2,
    calcio_mg: 21,
    ferro_mg: 1.8,
    zinco_mg: 0.7,
    vitamina_c_mg: 0,
    vitamina_a_ra: 0,
    porcao: "100g",
    medida_caseira: "2 colheres de sopa",
  },
  {
    id: 3,
    nome: "Peito de frango grelhado",
    categoria: "Carnes",
    energia_kcal: 165,
    proteina_g: 31,
    lipideos_g: 3.6,
    carboidrato_g: 0,
    fibra_alimentar_g: 0,
    calcio_mg: 11,
    ferro_mg: 0.9,
    zinco_mg: 1.2,
    vitamina_c_mg: 0,
    vitamina_a_ra: 7,
    porcao: "100g",
    medida_caseira: "1 filé médio",
  },
  {
    id: 4,
    nome: "Alho",
    categoria: "Temperos",
    energia_kcal: 149,
    proteina_g: 6.4,
    lipideos_g: 0.5,
    carboidrato_g: 33,
    fibra_alimentar_g: 2.1,
    calcio_mg: 201,
    ferro_mg: 3.2,
    zinco_mg: 2.6,
    vitamina_c_mg: 31,
    vitamina_a_ra: 0,
    porcao: "100g",
    medida_caseira: "10 dentes",
  },
  {
    id: 5,
    nome: "Cebola",
    categoria: "Temperos",
    energia_kcal: 41,
    proteina_g: 1.1,
    lipideos_g: 0.1,
    carboidrato_g: 10,
    fibra_alimentar_g: 1.7,
    calcio_mg: 23,
    ferro_mg: 0.3,
    zinco_mg: 0.2,
    vitamina_c_mg: 7.4,
    vitamina_a_ra: 0,
    porcao: "100g",
    medida_caseira: "1 cebola média",
  },
  {
    id: 6,
    nome: "Tomate",
    categoria: "Hortaliças",
    energia_kcal: 18,
    proteina_g: 0.9,
    lipideos_g: 0.2,
    carboidrato_g: 3.9,
    fibra_alimentar_g: 1.2,
    calcio_mg: 10,
    ferro_mg: 0.3,
    zinco_mg: 0.2,
    vitamina_c_mg: 13.7,
    vitamina_a_ra: 42,
    porcao: "100g",
    medida_caseira: "1 tomate médio",
  },
  {
    id: 7,
    nome: "Brócolis",
    categoria: "Hortaliças",
    energia_kcal: 34,
    proteina_g: 2.8,
    lipideos_g: 0.4,
    carboidrato_g: 7,
    fibra_alimentar_g: 2.6,
    calcio_mg: 47,
    ferro_mg: 0.7,
    zinco_mg: 0.4,
    vitamina_c_mg: 89,
    vitamina_a_ra: 31,
    porcao: "100g",
    medida_caseira: "1 ramo",
  },
  {
    id: 8,
    nome: "Espinafre",
    categoria: "Hortaliças",
    energia_kcal: 23,
    proteina_g: 2.9,
    lipideos_g: 0.4,
    carboidrato_g: 3.6,
    fibra_alimentar_g: 2.2,
    calcio_mg: 99,
    ferro_mg: 2.7,
    zinco_mg: 0.5,
    vitamina_c_mg: 28,
    vitamina_a_ra: 469,
    porcao: "100g",
    medida_caseira: "2 folhas grandes",
  },
  {
    id: 9,
    nome: "Cenoura",
    categoria: "Hortaliças",
    energia_kcal: 41,
    proteina_g: 0.9,
    lipideos_g: 0.2,
    carboidrato_g: 10,
    fibra_alimentar_g: 2.8,
    calcio_mg: 33,
    ferro_mg: 0.3,
    zinco_mg: 0.2,
    vitamina_c_mg: 5.9,
    vitamina_a_ra: 835,
    porcao: "100g",
    medida_caseira: "1 cenoura média",
  },
  {
    id: 10,
    nome: "Batata-doce",
    categoria: "Tubérculos",
    energia_kcal: 86,
    proteina_g: 1.6,
    lipideos_g: 0.1,
    carboidrato_g: 20,
    fibra_alimentar_g: 3,
    calcio_mg: 30,
    ferro_mg: 0.6,
    zinco_mg: 0.3,
    vitamina_c_mg: 2.4,
    vitamina_a_ra: 709,
    porcao: "100g",
    medida_caseira: "1 batata média",
  },
  {
    id: 11,
    nome: "Batata common",
    categoria: "Tubérculos",
    energia_kcal: 77,
    proteina_g: 2,
    lipideos_g: 0.1,
    carboidrato_g: 17,
    fibra_alimentar_g: 2.2,
    calcio_mg: 12,
    ferro_mg: 0.8,
    zinco_mg: 0.3,
    vitamina_c_mg: 19.7,
    vitamina_a_ra: 0,
    porcao: "100g",
    medida_caseira: "1 batata média",
  },
  {
    id: 12,
    nome: "Macarrão cozido",
    categoria: "Cereais e derivados",
    energia_kcal: 131,
    proteina_g: 5.1,
    lipideos_g: 1.1,
    carboidrato_g: 25,
    fibra_alimentar_g: 1.2,
    calcio_mg: 7,
    ferro_mg: 1.3,
    zinco_mg: 0.7,
    vitamina_c_mg: 0,
    vitamina_a_ra: 0,
    porcao: "100g",
    medida_caseira: "1 prato",
  },
  {
    id: 13,
    nome: "Pão francês",
    categoria: "Cereais e derivados",
    energia_kcal: 265,
    proteina_g: 9.3,
    lipideos_g: 3.2,
    carboidrato_g: 49,
    fibra_alimentar_g: 2.3,
    calcio_mg: 133,
    ferro_mg: 2.7,
    zinco_mg: 1.1,
    vitamina_c_mg: 0,
    vitamina_a_ra: 0,
    porcao: "100g",
    medida_caseira: "1 pão",
  },
  {
    id: 14,
    nome: "Leite integral",
    categoria: "Leite e derivados",
    energia_kcal: 61,
    proteina_g: 3.2,
    lipideos_g: 3.3,
    carboidrato_g: 4.8,
    fibra_alimentar_g: 0,
    calcio_mg: 113,
    ferro_mg: 0.1,
    zinco_mg: 0.4,
    vitamina_c_mg: 1.5,
    vitamina_a_ra: 46,
    porcao: "100ml",
    medida_caseira: "1 copo",
  },
  {
    id: 15,
    nome: "Leite desnatado",
    categoria: "Leite e derivados",
    energia_kcal: 35,
    proteina_g: 3.4,
    lipideos_g: 0.1,
    carboidrato_g: 5,
    fibra_alimentar_g: 0,
    calcio_mg: 125,
    ferro_mg: 0,
    zinco_mg: 0.4,
    vitamina_c_mg: 0,
    vitamina_a_ra: 204,
    porcao: "100ml",
    medida_caseira: "1 copo",
  },
  {
    id: 16,
    nome: "Iogurte natural",
    categoria: "Leite e derivados",
    energia_kcal: 59,
    proteina_g: 3.5,
    lipideos_g: 3.3,
    carboidrato_g: 4.5,
    fibra_alimentar_g: 0,
    calcio_mg: 128,
    ferro_mg: 0.1,
    zinco_mg: 0.5,
    vitamina_c_mg: 0.5,
    vitamina_a_ra: 14,
    porcao: "100g",
    medida_caseira: "1 pote",
  },
  {
    id: 17,
    nome: "Queijo mussarela",
    categoria: "Leite e derivados",
    energia_kcal: 303,
    proteina_g: 22,
    lipideos_g: 22,
    carboidrato_g: 2.2,
    fibra_alimentar_g: 0,
    calcio_mg: 505,
    ferro_mg: 0.3,
    zinco_mg: 2.5,
    vitamina_c_mg: 0,
    vitamina_a_ra: 99,
    porcao: "100g",
    medida_caseira: "4 fatias",
  },
  {
    id: 18,
    nome: "Ovo cozido",
    categoria: "Ovos e derivados",
    energia_kcal: 155,
    proteina_g: 13,
    lipideos_g: 11,
    carboidrato_g: 1.1,
    fibra_alimentar_g: 0,
    calcio_mg: 50,
    ferro_mg: 1.2,
    zinco_mg: 1,
    vitamina_c_mg: 0,
    vitamina_a_ra: 162,
    porcao: "100g",
    medida_caseira: "2 ovos",
  },
  {
    id: 19,
    nome: "Salmão grelhado",
    categoria: "Pescados",
    energia_kcal: 208,
    proteina_g: 20,
    lipideos_g: 13,
    carboidrato_g: 0,
    fibra_alimentar_g: 0,
    calcio_mg: 15,
    ferro_mg: 0.5,
    zinco_mg: 0.5,
    vitamina_c_mg: 0,
    vitamina_a_ra: 15,
    porcao: "100g",
    medida_caseira: "1 filé",
  },
  {
    id: 20,
    nome: "Atum enlatado",
    categoria: "Pescados",
    energia_kcal: 116,
    proteina_g: 26,
    lipideos_g: 0.8,
    carboidrato_g: 0,
    fibra_alimentar_g: 0,
    calcio_mg: 12,
    ferro_mg: 1.4,
    zinco_mg: 0.6,
    vitamina_c_mg: 0,
    vitamina_a_ra: 30,
    porcao: "100g",
    medida_caseira: "1 lata",
  },
  {
    id: 21,
    nome: "Azeite de oliva",
    categoria: "Gorduras",
    energia_kcal: 884,
    proteina_g: 0,
    lipideos_g: 100,
    carboidrato_g: 0,
    fibra_alimentar_g: 0,
    calcio_mg: 1,
    ferro_mg: 0.6,
    zinco_mg: 0,
    vitamina_c_mg: 0,
    vitamina_a_ra: 0,
    porcao: "100ml",
    medida_caseira: "7 colheres de sopa",
  },
  {
    id: 22,
    nome: "Óleo de soja",
    categoria: "Gorduras",
    energia_kcal: 884,
    proteina_g: 0,
    lipideos_g: 100,
    carboidrato_g: 0,
    fibra_alimentar_g: 0,
    calcio_mg: 0,
    ferro_mg: 0,
    zinco_mg: 0,
    vitamina_c_mg: 0,
    vitamina_a_ra: 0,
    porcao: "100ml",
    medida_caseira: "7 colheres de sopa",
  },
  {
    id: 23,
    nome: "Manteiga",
    categoria: "Gorduras",
    energia_kcal: 717,
    proteina_g: 0.8,
    lipideos_g: 81,
    carboidrato_g: 0.1,
    fibra_alimentar_g: 0,
    calcio_mg: 24,
    ferro_mg: 0,
    zinco_mg: 0.1,
    vitamina_c_mg: 0.6,
    vitamina_a_ra: 249,
    porcao: "100g",
    medida_caseira: "7 colheres de sopa",
  },
  {
    id: 24,
    nome: "Banana",
    categoria: "Frutas",
    energia_kcal: 89,
    proteina_g: 1.1,
    lipideos_g: 0.3,
    carboidrato_g: 23,
    fibra_alimentar_g: 2.6,
    calcio_mg: 5,
    ferro_mg: 0.3,
    zinco_mg: 0.2,
    vitamina_c_mg: 8.7,
    vitamina_a_ra: 30,
    porcao: "100g",
    medida_caseira: "1 banana média",
  },
  {
    id: 25,
    nome: "Maçã",
    categoria: "Frutas",
    energia_kcal: 52,
    proteina_g: 0.3,
    lipideos_g: 0.2,
    carboidrato_g: 14,
    fibra_alimentar_g: 2.4,
    calcio_mg: 6,
    ferro_mg: 0.1,
    zinco_mg: 0,
    vitamina_c_mg: 4.6,
    vitamina_a_ra: 3,
    porcao: "100g",
    medida_caseira: "1 maçã média",
  },
  {
    id: 26,
    nome: "Laranja",
    categoria: "Frutas",
    energia_kcal: 47,
    proteina_g: 0.9,
    lipideos_g: 0.1,
    carboidrato_g: 12,
    fibra_alimentar_g: 2.4,
    calcio_mg: 40,
    ferro_mg: 0.1,
    zinco_mg: 0.1,
    vitamina_c_mg: 53.2,
    vitamina_a_ra: 11,
    porcao: "100g",
    medida_caseira: "1 laranja média",
  },
  {
    id: 27,
    nome: "Mamão",
    categoria: "Frutas",
    energia_kcal: 43,
    proteina_g: 0.5,
    lipideos_g: 0.3,
    carboidrato_g: 11,
    fibra_alimentar_g: 1.7,
    calcio_mg: 31,
    ferro_mg: 0.2,
    zinco_mg: 0.1,
    vitamina_c_mg: 60.9,
    vitamina_a_ra: 109,
    porcao: "100g",
    medida_caseira: "1 fatia",
  },
  {
    id: 28,
    nome: "Abacate",
    categoria: "Frutas",
    energia_kcal: 160,
    proteina_g: 2,
    lipideos_g: 15,
    carboidrato_g: 9,
    fibra_alimentar_g: 6.7,
    calcio_mg: 12,
    ferro_mg: 0.6,
    zinco_mg: 0.6,
    vitamina_c_mg: 10,
    vitamina_a_ra: 7,
    porcao: "100g",
    medida_caseira: "1/2 abacate",
  },
  {
    id: 29,
    nome: "Morango",
    categoria: "Frutas",
    energia_kcal: 32,
    proteina_g: 0.7,
    lipideos_g: 0.3,
    carboidrato_g: 7.7,
    fibra_alimentar_g: 2,
    calcio_mg: 16,
    ferro_mg: 0.4,
    zinco_mg: 0.1,
    vitamina_c_mg: 58.8,
    vitamina_a_ra: 1,
    porcao: "100g",
    medida_caseira: "6 unidades",
  },
  {
    id: 30,
    nome: "Uva",
    categoria: "Frutas",
    energia_kcal: 69,
    proteina_g: 0.7,
    lipideos_g: 0.2,
    carboidrato_g: 18,
    fibra_alimentar_g: 0.9,
    calcio_mg: 10,
    ferro_mg: 0.4,
    zinco_mg: 0.1,
    vitamina_c_mg: 3.2,
    vitamina_a_ra: 3,
    porcao: "100g",
    medida_caseira: "12 bagos",
  },
  {
    id: 31,
    nome: "Melancia",
    categoria: "Frutas",
    energia_kcal: 30,
    proteina_g: 0.6,
    lipideos_g: 0.2,
    carboidrato_g: 7.6,
    fibra_alimentar_g: 0.4,
    calcio_mg: 7,
    ferro_mg: 0.2,
    zinco_mg: 0.1,
    vitamina_c_mg: 8.1,
    vitamina_a_ra: 28,
    porcao: "100g",
    medida_caseira: "1 fatia",
  },
  {
    id: 32,
    nome: "Abóbora",
    categoria: "Hortaliças",
    energia_kcal: 26,
    proteina_g: 1,
    lipideos_g: 0.3,
    carboidrato_g: 6,
    fibra_alimentar_g: 2.1,
    calcio_mg: 10,
    ferro_mg: 0.4,
    zinco_mg: 0.2,
    vitamina_c_mg: 106,
    vitamina_a_ra: 51,
    porcao: "100g",
    medida_caseira: "1/2 Pimentão",
  },
  {
    id: 45,
    nome: "Cogumelo",
    categoria: "Hortaliças",
    energia_kcal: 22,
    proteina_g: 2.2,
    lipideos_g: 0.3,
    carboidrato_g: 3.3,
    fibra_alimentar_g: 1,
    calcio_mg: 3,
    ferro_mg: 0.5,
    zinco_mg: 0.5,
    vitamina_c_mg: 0,
    vitamina_a_ra: 0,
    porcao: "100g",
    medida_caseira: "1 xícara",
  },
];

export function searchFoods(query: string): TacoEntry[] {
  const q = query.toLowerCase();
  return tacoDatabase
    .filter(
      (food) =>
        food.nome.toLowerCase().includes(q) ||
        food.categoria.toLowerCase().includes(q),
    )
    .slice(0, 10);
}

export function getFoodById(id: number): TacoEntry | undefined {
  return tacoDatabase.find((food) => food.id === id);
}

export function getFoodsByCategory(category: string): TacoEntry[] {
  return tacoDatabase.filter((food) => food.categoria === category);
}

export function calculateNutrition(
  foods: { foodId: number; quantity: number }[],
): {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
} {
  let calories = 0,
    protein = 0,
    carbs = 0,
    fat = 0,
    fiber = 0;

  for (const item of foods) {
    const food = getFoodById(item.foodId);
    if (food) {
      const factor = item.quantity / 100;
      calories += food.energia_kcal * factor;
      protein += food.proteina_g * factor;
      carbs += food.carboidrato_g * factor;
      fat += food.lipideos_g * factor;
      fiber += food.fibra_alimentar_g * factor;
    }
  }

  return {
    calories: Math.round(calories),
    protein: Math.round(protein),
    carbs: Math.round(carbs),
    fat: Math.round(fat),
    fiber: Math.round(fiber),
  };
}

export const scientificReferences = [
  {
    id: 1,
    title: "Tabela Brasileira de Composição de Alimentos (TACO)",
    source: "UNICAMP",
    year: 2011,
  },
  {
    id: 2,
    title: "Dietary Reference Intakes (DRI)",
    source: "Institute of Medicine",
    year: 2011,
  },
  {
    id: 3,
    title: "Guia Alimentar para a População Brasileira",
    source: "Ministério da Saúde",
    year: 2014,
  },
  {
    id: 4,
    title: "American Dietetic Association Position Paper",
    source: "ADA",
    year: 2008,
  },
  {
    id: 5,
    title: "World Health Organization Diet Guidelines",
    source: "WHO",
    year: 2020,
  },
];
